/* 389. Find the Difference

Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t. */
#include <iostream>
#include <string>
char findTheDifference(std::string s, std::string t);
int main()
{
    std::string s = "abcd", t = "abcde";
    std::cout << findTheDifference(s, t);
    return NULL;
}

char findTheDifference(std::string s, std::string t) {
    int diff = t[(int)(t.length()-1)];
    for (int i = 0; i < s.length(); i++) {
        diff = diff ^ ((int)t[i]) ^ (int)s[i];
    }
    return (char)diff;
}